// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IconAppChordDiagram: typeof import('~icons/app/chord-diagram')['default']
    IconAppTuningFork: typeof import('~icons/app/tuning-fork')['default']
    'IconBi:arrowDown': typeof import('~icons/bi/arrow-down')['default']
    'IconBi:arrowUp': typeof import('~icons/bi/arrow-up')['default']
    'IconBi:chevronDown': typeof import('~icons/bi/chevron-down')['default']
    'IconBi:chevronLeft': typeof import('~icons/bi/chevron-left')['default']
    'IconBi:chevronRight': typeof import('~icons/bi/chevron-right')['default']
    'IconBi:file': typeof import('~icons/bi/file')['default']
    'IconBi:journalPlus': typeof import('~icons/bi/journal-plus')['default']
    'IconBi:journalText': typeof import('~icons/bi/journal-text')['default']
    'IconBi:layoutThreeColumns': typeof import('~icons/bi/layout-three-columns')['default']
    'IconBi:mic': typeof import('~icons/bi/mic')['default']
    'IconBi:micFill': typeof import('~icons/bi/mic-fill')['default']
    'IconBi:search': typeof import('~icons/bi/search')['default']
    'IconBiLayoutThreeColumns\"': typeof import('~icons/bi/layout-three-columns/"')['default']
  }
}

export { }
