// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IconAppChordDiagram: typeof import('~icons/app/chord-diagram')['default']
    'IconAppLayoutThreeColumns\"': typeof import('~icons/app/layout-three-columns/"')['default']
    'IconBi:file': typeof import('~icons/bi/file')['default']
    'IconBi:journalText': typeof import('~icons/bi/journal-text')['default']
    'IconBi:layoutThreeColumns': typeof import('~icons/bi/layout-three-columns')['default']
    'IconBi:layoutThreeColumns\"': typeof import('~icons/bi/layout-three-columns/"')['default']
    IconBiFile: typeof import('~icons/bi/file')['default']
    IconBiJournalPlus: typeof import('~icons/bi/journal-plus')['default']
    'IconBiLayoutThreeColumns\"': typeof import('~icons/bi/layout-three-columns/"')['default']
  }
}

export { }
